USE [master]
GO

/****** Object:  Database [Synapse]    Script Date: 08/16/2010 22:13:18 ******/
CREATE DATABASE [Synapse] ON  PRIMARY 
( NAME = N'Synapse_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Synapse.MDF' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB )
 LOG ON 
( NAME = N'Synapse_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Synapse.LDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [Synapse] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Synapse].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [Synapse] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Synapse] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Synapse] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Synapse] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Synapse] SET ARITHABORT OFF 
GO

ALTER DATABASE [Synapse] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Synapse] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Synapse] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [Synapse] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Synapse] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Synapse] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Synapse] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Synapse] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Synapse] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Synapse] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Synapse] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Synapse] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Synapse] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Synapse] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Synapse] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Synapse] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Synapse] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Synapse] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Synapse] SET  READ_WRITE 
GO

ALTER DATABASE [Synapse] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Synapse] SET  MULTI_USER 
GO

ALTER DATABASE [Synapse] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [Synapse] SET DB_CHAINING OFF 
GO

